services:
  dev-db:
    image: postgres:bullseye
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    volumes:
      - pgdata:/var/lib/postgresql/data 
  test-db:
    image: postgres:bullseye
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
volumes:
  pgdata: